import { execFileSync } from "node:child_process";
import { relative } from "node:path";
import { registerAppTool } from "@modelcontextprotocol/ext-apps/server";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import * as z from "zod/v4";
import type { ServerConfig } from "./config.js";
import { logEvent } from "./logger.js";
import type { WorkspaceRegistry } from "./workspaces.js";

const WORKSPACE_APP_URI = "ui://devspace/workspace-app.html";
const READ_ANNOTATIONS = { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true };
const WRITE_ANNOTATIONS = { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true };
export interface CommandResult { ok: boolean; stdout: string; stderr: string; exitCode: number | null; error?: string; }
export function runGitCommand(cwd: string, args: string[], timeoutMs = 120_000): CommandResult {
  try { const stdout = execFileSync("git", args, { cwd, encoding: "utf8", windowsHide: true, timeout: timeoutMs, maxBuffer: 20 * 1024 * 1024 }); return { ok: true, stdout, stderr: "", exitCode: 0 }; }
  catch (error: unknown) { const failure = error as Error & { stdout?: string | Buffer; stderr?: string | Buffer; status?: number }; return { ok: false, stdout: typeof failure.stdout === "string" ? failure.stdout : failure.stdout?.toString() ?? "", stderr: typeof failure.stderr === "string" ? failure.stderr : failure.stderr?.toString() ?? "", exitCode: typeof failure.status === "number" ? failure.status : null, error: error instanceof Error ? error.message : String(error) }; }
}
export function validateGitRef(value: string | undefined, label: string): string | undefined { if (value === undefined) return undefined; if (!/^[A-Za-z0-9._\/-]+$/.test(value) || value.startsWith("-") || value.includes("..") || value.includes("//")) throw new Error(`${label} contains unsupported characters.`); return value; }
function widgetMeta(config: ServerConfig) { return config.widgets === "full" ? { _meta: { ui: { resourceUri: WORKSPACE_APP_URI, visibility: ["model"] } } } : { _meta: {} }; }
function outputSchema() { return { result: z.string(), ok: z.boolean(), exitCode: z.number().nullable(), stdout: z.string(), stderr: z.string(), error: z.string().nullable() }; }
function response(result: CommandResult) { const text = [result.stdout, result.stderr].filter(Boolean).join(result.stdout && result.stderr ? "\n" : "") || (result.ok ? "Git command completed successfully." : result.error ?? "Git command failed."); return { content: [{ type: "text" as const, text }], structuredContent: { result: text, ok: result.ok, exitCode: result.exitCode, stdout: result.stdout, stderr: result.stderr, error: result.error ?? null }, isError: result.ok ? undefined : true }; }
function log(config: ServerConfig, tool: string, startedAt: number, fields: Record<string, unknown>, success: boolean) { if (config.logging.toolCalls) logEvent(config.logging, success ? "info" : "warn", "tool_call", { tool, ...fields, success, durationMs: Math.round(performance.now() - startedAt) }); }
export function registerGitTools(server: McpServer, config: ServerConfig, workspaces: WorkspaceRegistry): void {
  registerAppTool(server, "git_status", { title: "Git Status", description: "Show Git status for an open workspace using git status -sb. Read-only and scoped to the workspace root.", inputSchema: { workspaceId: z.string() }, outputSchema: outputSchema(), ...widgetMeta(config), annotations: READ_ANNOTATIONS }, async ({ workspaceId }) => { const startedAt = performance.now(); const workspace = workspaces.getWorkspace(workspaceId); const result = runGitCommand(workspace.root, ["status", "-sb"]); log(config, "git_status", startedAt, { workspaceId }, result.ok); return response(result); });
  registerAppTool(server, "git_add", { title: "Git Add", description: "Stage specific workspace-relative paths with git add -- <paths>. Paths are validated to remain inside the open workspace.", inputSchema: { workspaceId: z.string(), paths: z.array(z.string().min(1)).min(1).max(200) }, outputSchema: outputSchema(), ...widgetMeta(config), annotations: WRITE_ANNOTATIONS }, async ({ workspaceId, paths }) => { const startedAt = performance.now(); const workspace = workspaces.getWorkspace(workspaceId); const safePaths = paths.map((path) => { const absolute = workspaces.resolvePath(workspace, path); return relative(workspace.root, absolute).replaceAll("\\", "/") || "."; }); const result = runGitCommand(workspace.root, ["add", "--", ...safePaths]); log(config, "git_add", startedAt, { workspaceId, paths: safePaths }, result.ok); return response(result); });
  registerAppTool(server, "git_commit", { title: "Git Commit", description: "Create a Git commit from already-staged changes in an open workspace. Git hooks are honored.", inputSchema: { workspaceId: z.string(), message: z.string().min(1).max(500) }, outputSchema: outputSchema(), ...widgetMeta(config), annotations: WRITE_ANNOTATIONS }, async ({ workspaceId, message }) => { const startedAt = performance.now(); const workspace = workspaces.getWorkspace(workspaceId); const result = runGitCommand(workspace.root, ["commit", "-m", message], 300_000); log(config, "git_commit", startedAt, { workspaceId }, result.ok); return response(result); });
  registerAppTool(server, "git_pull", { title: "Git Pull", description: "Pull from a configured Git remote. Remote and branch are passed without a shell.", inputSchema: { workspaceId: z.string(), remote: z.string().optional(), branch: z.string().optional(), rebase: z.boolean().optional() }, outputSchema: outputSchema(), ...widgetMeta(config), annotations: WRITE_ANNOTATIONS }, async ({ workspaceId, remote, branch, rebase }) => { const startedAt = performance.now(); const workspace = workspaces.getWorkspace(workspaceId); const safeRemote = validateGitRef(remote, "remote"); const safeBranch = validateGitRef(branch, "branch"); if (safeBranch && !safeRemote) throw new Error("branch requires remote for git_pull."); const args = ["pull"]; if (rebase !== undefined) args.push(rebase ? "--rebase" : "--no-rebase"); if (safeRemote) args.push(safeRemote); if (safeBranch) args.push(safeBranch); const result = runGitCommand(workspace.root, args, 300_000); log(config, "git_pull", startedAt, { workspaceId, remote: safeRemote, branch: safeBranch }, result.ok); return response(result); });
  registerAppTool(server, "git_push", { title: "Git Push", description: "Push an open workspace to a configured Git remote with optional upstream setup.", inputSchema: { workspaceId: z.string(), remote: z.string().optional(), branch: z.string().optional(), setUpstream: z.boolean().optional() }, outputSchema: outputSchema(), ...widgetMeta(config), annotations: WRITE_ANNOTATIONS }, async ({ workspaceId, remote, branch, setUpstream }) => { const startedAt = performance.now(); const workspace = workspaces.getWorkspace(workspaceId); const safeRemote = validateGitRef(remote, "remote"); const safeBranch = validateGitRef(branch, "branch"); if (safeBranch && !safeRemote) throw new Error("branch requires remote for git_push."); const args = ["push"]; if (setUpstream) args.push("--set-upstream"); if (safeRemote) args.push(safeRemote); if (safeBranch) args.push(safeBranch); const result = runGitCommand(workspace.root, args, 300_000); log(config, "git_push", startedAt, { workspaceId, remote: safeRemote, branch: safeBranch }, result.ok); return response(result); });
}
